name: {{project_name.snakeCase()}}_ui
description: {{project_name.pascalCase()}} UI library
version: 0.0.1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: 3.22.3

dependencies:
  flutter:
    sdk: flutter
  flutter_asset_generator: ^1.1.0
  flutter_svg: ^2.0.10+1
  mockingjay: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: NotoSansDisplay
      fonts:
        - asset: assets/fonts/NotoSansDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansDisplay-SemiBold.ttf
          weight: 600

flutter_gen:
  assets:
    output:
      package_parameter_enabled: true
  line_length: 80

  integrations:
    flutter_svg: true
