name: auth_client
description: An authentication client implementation
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  rxdart: ^0.27.7
  token_provider:
    path: ../token_provider

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
