name: api_client

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/api_client/**"
      - ".github/workflows/api_client.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      dart_sdk: 3.3.0
      working_directory: packages/api_client
      coverage_excludes: "**/*.g.dart"
      min_coverage: 95