name: {{project_name}}_ui

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/{{project_name}}_ui/**"
      - ".github/workflows/{{project_name}}_ui.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      coverage_excludes: "**/*.g.dart"
      flutter_channel: stable
      flutter_version: 3.29.2
      working_directory: packages/{{project_name}}_ui
      min_coverage: 80
      analyze_directories: lib gallery test
      format_directories: lib gallery test
