name: form_inputs
description: A Dart package which exposes reusable form inputs and validation rules
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  formz: ^0.7.0

dev_dependencies:
  test: ^1.25.8
  very_good_analysis: ^6.0.0
